### ISSUE TITLE
Vectorised Analysis Transform

### ISSUE THREAD

**Issue by CosmoMatt** [astro-informatics/s2wav#39]
Go through the functions within `analysis.py` and wherever possible move to a vectorised implementation.

**Comment by CosmoMatt** [comment]
@JessWhitney this might be a good next issue for you to pick up!

**Comment by JessWhitney** [comment]
> @JessWhitney this might be a good next issue for you to pick up!

Yeah I'll take a look at it this week, will be a good opportunity for me to understand vectorisation better.
